import { StyleSheet } from 'react-native';

export const palette = {
  blue: '#3B82F6',
  blueDark: '#2563EB',
  bgTop: '#F6F8FC',
  bgBottom: '#E8F0FF',
  card: '#FFFFFF',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  border: '#E5E7EB',
  white: '#FFFFFF',
  danger: '#DC2626',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.bgTop,
  },
  flex: {
    flex: 1,
  },
  backgroundRoot: {
    ...StyleSheet.absoluteFillObject,
  },
  abstractShape: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: '#DBEAFE',
    opacity: 0.42,
  },
  abstractShapeTop: {
    width: 250,
    height: 250,
    top: -60,
    right: -70,
  },
  abstractShapeMid: {
    width: 180,
    height: 180,
    top: 120,
    left: -60,
    backgroundColor: '#E0E7FF',
    opacity: 0.32,
  },
  abstractShapeBottom: {
    width: 240,
    height: 240,
    bottom: -80,
    left: -70,
    backgroundColor: '#BFDBFE',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingVertical: 26,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: '#0F172A',
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  subheading: {
    marginTop: 10,
    fontSize: 14,
    color: palette.textSecondary,
    textAlign: 'center',
    lineHeight: 21,
  },
  statusPill: {
    marginTop: 18,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(59,130,246,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(147,197,253,0.55)',
  },
  statusPillText: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.15,
  },
  formWrap: {
    marginTop: 24,
  },
  formPanel: {
    gap: 2,
  },
  fieldBlock: {
    marginBottom: 16,
  },
  fieldLabel: {
    marginBottom: 8,
    marginLeft: 4,
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  inputShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(203,213,225,0.9)',
    backgroundColor: 'rgba(248,250,252,0.98)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: '#0F172A',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  inputShellFocused: {
    borderColor: '#2563EB',
    backgroundColor: '#FFFFFF',
    shadowColor: '#2563EB',
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  leadingIcon: {
    width: 18,
    marginRight: 12,
    color: '#64748B',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '700',
  },
  input: {
    flex: 1,
    color: '#0F172A',
    fontSize: 15,
    paddingVertical: 0,
  },
  trailingIconButton: {
    marginLeft: 12,
  },
  trailingIcon: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '700',
  },
  forgotWrap: {
    alignSelf: 'flex-end',
    marginTop: 4,
    marginBottom: 18,
  },
  forgotText: {
    color: palette.blue,
    fontSize: 14,
    fontWeight: '600',
  },
  errorText: {
    marginTop: 14,
    color: palette.danger,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  footerSwitch: {
    marginTop: 18,
    alignSelf: 'center',
  },
  footerText: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  footerAction: {
    color: palette.blue,
    fontWeight: '700',
  },
  primaryBtn: {
    marginTop: 8,
  },
});
